/* ============================================================================
   cities.js — офлайн-список городов.
   Используется как подсказка в поиске и как резерв, если геокодер Open-Meteo
   недоступен (нет сети / лимит запросов). Основной поиск всё равно идёт через
   https://geocoding-api.open-meteo.com — там находятся любые города мира.
   ========================================================================== */
window.PRESET_CITIES = [
  { name: 'Москва',          country: 'Россия',          admin1: 'Москва',            latitude: 55.7522,  longitude: 37.6156,   timezone: 'Europe/Moscow' },
  { name: 'Санкт-Петербург', country: 'Россия',          admin1: 'Санкт-Петербург',   latitude: 59.9386,  longitude: 30.3141,   timezone: 'Europe/Moscow' },
  { name: 'Новосибирск',     country: 'Россия',          admin1: 'Новосибирская',     latitude: 55.0415,  longitude: 82.9346,   timezone: 'Asia/Novosibirsk' },
  { name: 'Екатеринбург',    country: 'Россия',          admin1: 'Свердловская',      latitude: 56.8519,  longitude: 60.6122,   timezone: 'Asia/Yekaterinburg' },
  { name: 'Казань',          country: 'Россия',          admin1: 'Татарстан',         latitude: 55.7887,  longitude: 49.1221,   timezone: 'Europe/Moscow' },
  { name: 'Сочи',            country: 'Россия',          admin1: 'Краснодарский край',latitude: 43.6028,  longitude: 39.7342,   timezone: 'Europe/Moscow' },
  { name: 'Владивосток',     country: 'Россия',          admin1: 'Приморский край',   latitude: 43.1056,  longitude: 131.8735,  timezone: 'Asia/Vladivostok' },
  { name: 'Якутск',          country: 'Россия',          admin1: 'Якутия',            latitude: 62.0355,  longitude: 129.6755,  timezone: 'Asia/Yakutsk' },
  { name: 'Мурманск',        country: 'Россия',          admin1: 'Мурманская',        latitude: 68.9792,  longitude: 33.0925,   timezone: 'Europe/Moscow' },
  { name: 'Калининград',     country: 'Россия',          admin1: 'Калининградская',   latitude: 54.7065,  longitude: 20.5110,   timezone: 'Europe/Kaliningrad' },
  { name: 'Минск',           country: 'Беларусь',        admin1: 'Минск',             latitude: 53.9000,  longitude: 27.5667,   timezone: 'Europe/Minsk' },
  { name: 'Киев',            country: 'Украина',         admin1: 'Киев',              latitude: 50.4547,  longitude: 30.5238,   timezone: 'Europe/Kyiv' },
  { name: 'Алматы',          country: 'Казахстан',       admin1: 'Алматы',            latitude: 43.2567,  longitude: 76.9286,   timezone: 'Asia/Almaty' },
  { name: 'Астана',          country: 'Казахстан',       admin1: 'Астана',            latitude: 51.1801,  longitude: 71.4460,   timezone: 'Asia/Almaty' },
  { name: 'Ташкент',         country: 'Узбекистан',      admin1: 'Ташкент',           latitude: 41.2646,  longitude: 69.2163,   timezone: 'Asia/Tashkent' },
  { name: 'Тбилиси',         country: 'Грузия',          admin1: 'Тбилиси',           latitude: 41.6941,  longitude: 44.8337,   timezone: 'Asia/Tbilisi' },
  { name: 'Ереван',          country: 'Армения',         admin1: 'Ереван',            latitude: 40.1811,  longitude: 44.5136,   timezone: 'Asia/Yerevan' },
  { name: 'Баку',            country: 'Азербайджан',     admin1: 'Баку',              latitude: 40.3777,  longitude: 49.8920,   timezone: 'Asia/Baku' },
  { name: 'Бишкек',          country: 'Кыргызстан',      admin1: 'Бишкек',            latitude: 42.8700,  longitude: 74.5900,   timezone: 'Asia/Bishkek' },
  { name: 'Стамбул',         country: 'Турция',          admin1: 'Стамбул',           latitude: 41.0138,  longitude: 28.9497,   timezone: 'Europe/Istanbul' },
  { name: 'Лондон',          country: 'Великобритания',  admin1: 'Англия',            latitude: 51.5085,  longitude: -0.1257,   timezone: 'Europe/London' },
  { name: 'Берлин',          country: 'Германия',        admin1: 'Берлин',            latitude: 52.5244,  longitude: 13.4105,   timezone: 'Europe/Berlin' },
  { name: 'Париж',           country: 'Франция',         admin1: 'Иль-де-Франс',      latitude: 48.8534,  longitude: 2.3488,    timezone: 'Europe/Paris' },
  { name: 'Рим',             country: 'Италия',          admin1: 'Лацио',             latitude: 41.8919,  longitude: 12.5113,   timezone: 'Europe/Rome' },
  { name: 'Мадрид',          country: 'Испания',         admin1: 'Мадрид',            latitude: 40.4165,  longitude: -3.7026,   timezone: 'Europe/Madrid' },
  { name: 'Прага',           country: 'Чехия',           admin1: 'Прага',             latitude: 50.0880,  longitude: 14.4208,   timezone: 'Europe/Prague' },
  { name: 'Вена',            country: 'Австрия',         admin1: 'Вена',              latitude: 48.2085,  longitude: 16.3721,   timezone: 'Europe/Vienna' },
  { name: 'Амстердам',       country: 'Нидерланды',      admin1: 'Северная Голландия',latitude: 52.3740,  longitude: 4.8897,    timezone: 'Europe/Amsterdam' },
  { name: 'Хельсинки',       country: 'Финляндия',       admin1: 'Уусимаа',           latitude: 60.1695,  longitude: 24.9354,   timezone: 'Europe/Helsinki' },
  { name: 'Стокгольм',       country: 'Швеция',          admin1: 'Стокгольм',         latitude: 59.3326,  longitude: 18.0649,   timezone: 'Europe/Stockholm' },
  { name: 'Рейкьявик',       country: 'Исландия',        admin1: 'Хёвюдборгарсвайдид',latitude: 64.1355,  longitude: -21.8954,  timezone: 'Atlantic/Reykjavik' },
  { name: 'Дубай',           country: 'ОАЭ',             admin1: 'Дубай',             latitude: 25.0657,  longitude: 55.1713,   timezone: 'Asia/Dubai' },
  { name: 'Токио',           country: 'Япония',          admin1: 'Токио',             latitude: 35.6895,  longitude: 139.6917,  timezone: 'Asia/Tokyo' },
  { name: 'Киото',           country: 'Япония',          admin1: 'Киото',             latitude: 35.0116,  longitude: 135.7681,  timezone: 'Asia/Tokyo' },
  { name: 'Сеул',            country: 'Южная Корея',     admin1: 'Сеул',              latitude: 37.5660,  longitude: 126.9784,  timezone: 'Asia/Seoul' },
  { name: 'Пекин',           country: 'Китай',           admin1: 'Пекин',             latitude: 39.9075,  longitude: 116.3972,  timezone: 'Asia/Shanghai' },
  { name: 'Бангкок',         country: 'Таиланд',         admin1: 'Бангкок',           latitude: 13.7539,  longitude: 100.5014,  timezone: 'Asia/Bangkok' },
  { name: 'Сингапур',        country: 'Сингапур',        admin1: '',                  latitude: 1.2897,   longitude: 103.8501,  timezone: 'Asia/Singapore' },
  { name: 'Дели',            country: 'Индия',           admin1: 'Дели',              latitude: 28.6519,  longitude: 77.2315,   timezone: 'Asia/Kolkata' },
  { name: 'Нью-Йорк',        country: 'США',             admin1: 'Нью-Йорк',          latitude: 40.7143,  longitude: -74.0060,  timezone: 'America/New_York' },
  { name: 'Чикаго',          country: 'США',             admin1: 'Иллинойс',          latitude: 41.8500,  longitude: -87.6500,  timezone: 'America/Chicago' },
  { name: 'Лос-Анджелес',    country: 'США',             admin1: 'Калифорния',        latitude: 34.0522,  longitude: -118.2437, timezone: 'America/Los_Angeles' },
  { name: 'Торонто',         country: 'Канада',          admin1: 'Онтарио',           latitude: 43.7001,  longitude: -79.4163,  timezone: 'America/Toronto' },
  { name: 'Мехико',          country: 'Мексика',         admin1: 'Мехико',            latitude: 19.4326,  longitude: -99.1332,  timezone: 'America/Mexico_City' },
  { name: 'Рио-де-Жанейро',  country: 'Бразилия',        admin1: 'Рио-де-Жанейро',    latitude: -22.9068, longitude: -43.1729,  timezone: 'America/Sao_Paulo' },
  { name: 'Буэнос-Айрес',    country: 'Аргентина',       admin1: 'Буэнос-Айрес',      latitude: -34.6132, longitude: -58.3772,  timezone: 'America/Argentina/Buenos_Aires' },
  { name: 'Каир',            country: 'Египет',          admin1: 'Каир',              latitude: 30.0626,  longitude: 31.2497,   timezone: 'Africa/Cairo' },
  { name: 'Кейптаун',        country: 'ЮАР',             admin1: 'Западный Кейп',     latitude: -33.9258, longitude: 18.4232,   timezone: 'Africa/Johannesburg' },
  { name: 'Сидней',          country: 'Австралия',       admin1: 'Новый Южный Уэльс', latitude: -33.8679, longitude: 151.2070,  timezone: 'Australia/Sydney' },
  { name: 'Окленд',          country: 'Новая Зеландия',  admin1: 'Окленд',            latitude: -36.8485, longitude: 174.7633,  timezone: 'Pacific/Auckland' }
];
